/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.lang.ArrayIndexOutOfBoundsException;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import java.lang.ArrayIndexOutOfBoundsException;
/**
 *
 * @author user
 */
public class Enrolment_student extends javax.swing.JFrame {

    /**
     * Creates new form Enrolment_student
     */
    Enrolment_student() {
        initComponents();
        setSize(600,360);
        setLocationRelativeTo(null);
        
        Refresh();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("신청하기");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("수강신청");

        jButton2.setText("종료");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String lectureName;
String namee;
String str1;
String str2;
String str3;
    public void name(String a){
         namee = a; // 로그인한 학생의 이름 받아온거 ;
    }
     public void numberr(String b){
         str2 = b; // 로그인한 학생의 학번 받아온거 
    }
     public void majorr(String c){
         str3 = c; // 로그인한 학생의 학과 받아온거 
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String str1 = null;
        String str2 = null;
        try{
        int row = jTable1.getSelectedRow();
        if (Integer.parseInt(jTable1.getValueAt(row, 4).toString()) >= Integer.parseInt(jTable1.getValueAt(row, 5).toString())) {
            JOptionPane.showMessageDialog(null, "최대인원을 초과 한 강의입니다.");
        }


        
       File file = new File("student.txt");
        try{
            BufferedReader bufReader = new BufferedReader(new InputStreamReader(new FileInputStream(file),"euc-kr"));
            String line = "";
            int i = 1;
            while((line = bufReader.readLine()) != null){
                String[] splitedStr = line.split("/");
                if(splitedStr[0].equals(namee)){               
             str1 = splitedStr[1];
             str2 = splitedStr[2]; // str1 학번 str2 이름
              line=" ";      
              }

            }
            bufReader.close();
        } catch(FileNotFoundException e){

        }catch(IOException e){
            System.out.println(e);
        }
        
        String str3 = jTable1.getValueAt(row, 0).toString(); // 강좌번호
        String str4 = jTable1.getValueAt(row, 1).toString(); // 강좌명
        String str5 = jTable1.getValueAt(row, 2).toString(); // ?_?
        
        try{
            File myfile = new File(namee+".txt");
            BufferedReader read = new BufferedReader(new InputStreamReader(new FileInputStream(myfile),"UTF8"));
            String line = "";
            String [] array;
            while((line = read.readLine()) != null){
                array = line.split("/");
                if (array[0].equals(str3)) {
                    JOptionPane.showMessageDialog(null, "이미 신청한 강좌입니다.");
                    return;
                }
              }
            read.close();
        } catch(FileNotFoundException e){

        }catch(IOException e){
            System.out.println(e);
        }
        
                try{
                    //int row = jTable1.getSelectedRow();
                    BufferedWriter bos = new BufferedWriter(new FileWriter(namee+".txt",true));     
                    String strr =  str3 + "/" + str4 + "/" + str5 + "\n";
                    bos.write(strr);
                    bos.close();
                } catch (IOException ex) {
                    Logger.getLogger(Study_newstudy_modal.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    FileWriter reader;
                    //int row = jTable1.getSelectedRow();
                    String filename = jTable1.getValueAt(row, 1).toString(); // 강좌명
                    reader = new FileWriter(filename+".txt"); // 텍스트 파일이 없으면 새로 생성함!
                    try {
                        OutputStream output = new FileOutputStream(filename+".txt", true);
                        String str = namee+ "/" + str1 + "/" + str2; // 강좌명.txt에 내 이름 학번 학과를 넣음
                        byte[] by=str.getBytes();
                        output.write(by);
                        countLecture(str3);
                    } catch (Exception e) {
                         e.getStackTrace();
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Study_newstudy_modal.class.getName()).log(Level.SEVERE, null, ex);
                }
        } catch (ArrayIndexOutOfBoundsException e ) {
            JOptionPane.showMessageDialog(null, "강의를 선택하세요.");
        }
        
        Refresh();

      Enrolment1 m = new Enrolment1();
      m.name(namee);
     // String namee = name;
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void countLecture(String SLnumber) {
        int SLpoint = 1;
        try {
            String s; 
            String[] array;
            File myFile = new File("openlecture.txt");
            FileReader fileReader = new FileReader(myFile);
            BufferedReader reader = new BufferedReader(fileReader);
 	   int i=0;
            while ((s = reader.readLine()) != null) {
               array = s.split("/");
               if (array[3].equals(SLnumber)) {
                   SLpoint = i;
               }
               i += 1;
 	   }
 	   reader.close();
 	   } catch (IOException e2) { 
 	   e2.printStackTrace(); 
           }
        
                  File file = new File("openlecture.txt");		
		String dummy = "";
		try {
			BufferedReader br = new BufferedReader(new FileReader("openlecture.txt"));
			String line;
			for(int i=0; i<SLpoint; i++) {
			    line = br.readLine(); //읽으며 이동
			    dummy += (line + "\r\n" ); 
			}
                           String preData = br.readLine();
                           String [] array;
                           String newData = "";
                           array = preData.split("/");
                           for(int i=0;i<8;i++) {
                               newData += array[i]+"/";
                           }
                           newData += Integer.parseInt(array[8]) + 1;
                           dummy += newData+"\r\n";
			//Log.d("mstag","삭제되는 데이터 = "+delData);
			//3. 삭제하고자 하는 position 이후부터 dummy에 저장
			while((line = br.readLine())!=null) {
				dummy += (line + "\r\n" ); 
			}
			FileWriter fw = new FileWriter("openlecture.txt");
			fw.write(dummy);
			fw.close();
			br.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
    }
    
    public void Refresh() {
        String filePath = "openlecture.txt";
        File file = new File(filePath);
        
        jTable1.setModel(new DefaultTableModel(new Object[][][] {}, new String[] { "셀1","셀2","셀3" }){
        public boolean isCellEditable(int row, int column) {
             //all cells false
            return false;
         }
        }); // 더블클릭방지
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false); // 헤드라인 못옮기게
        
        try {
            BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(file),"UTF8"));
            //String firstLine = br.readLine().trim();
            String firstLine = "강좌번호/강좌명/학과/학점/신청인원/최대인원/설명";
            // 교수명0 / 최대1 / 최소2 / 강좌번호3 / 강좌이름4 / 학과5 / 학점 6/ 설명7 / 신청인원8
            String[] columnsName = firstLine.split("/");
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setColumnIdentifiers(columnsName);
            Object[] tableLines = br.lines().toArray();
            
            for(int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                String [] sortDB = {"","","","","","",""};
                sortDB[0] = dataRow[3] ; sortDB[1] = dataRow[4]; sortDB[2] = dataRow[5]; sortDB[3] = dataRow[6]; sortDB[4] = dataRow[8]; sortDB[5] = dataRow[1]; sortDB[6] = dataRow[7];
                model.addRow(sortDB);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Enrolment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        final TableColumnModel columnModel = jTable1.getColumnModel();
             for (int column = 0; column < jTable1.getColumnCount(); column++) { // 글자 크기에 맞춰서 행 크기 설정
        int width = 50; // Min width 
       for (int row = 0; row < jTable1.getRowCount(); row++) { 
        TableCellRenderer renderer = jTable1.getCellRenderer(row, column); 
        Component comp = jTable1.prepareRenderer(renderer, row, column); 
        width = Math.max(comp.getPreferredSize().width +1 , width); } 
        columnModel.getColumn(column).setPreferredWidth(width); }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enrolment_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enrolment_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enrolment_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enrolment_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // Student t = new Student();
                //String n = t.name();
               // String n = 
                new Enrolment_student();
              // Enrolment_student n = new Enrolment_student();
               //n.student();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
